### ISSUE TITLE
Negation doesn't work with ListField (exclude, ~Q). Get "Bad search filter" message.

### ISSUE THREAD

**Issue by ikreb7** [django-ldapdb/django-ldapdb#105]
Hello,
i want to get objects which doesn't contain certain values at the ListField.

I have the models   ``LdapUser`` and ``LdapGroup`` like the [github example](https://github.com/django-ldapdb/django-ldapdb/blob/master/examples/models.py).  And I want the query like:

``LdapGroup.objects.filter(~Q(usernames='cn=user1,{}'.format(LdapUser.base_dn)))``

I also tried:

``LdapGroup.objects.exclude(usernames='cn=user1,{}'.format(LdapUser.base_dn))``

But I still get the error message ``FILTER_ERROR: {'desc': 'Bad search filter'}``

I think it is a ldap error and come from pyldap, but it is only an assumption. 

Maybe it is a good idea to report at the documentation which methods ``django-ldapdb`` doesn't support.

**Comment by rbarrois** [comment]
Good catch; I'd label this as a bug / missing expected feature.
