### ISSUE TITLE
How to search for immediate children node?

### ISSUE THREAD

**Issue by zhuaiji** [django-ldapdb/django-ldapdb#108]
I want to search like this  'Searching for all employee and sub-department in a department' , or 'Searching for all immediate children nodes by a certain DN'.
I tried to code like this but failed
    `rootDN = request.GET.get('rootDN')`
   `CommonLdapObject.rootDN = rootDN`
    `resultList = CommonLdapObject.objects.all()`

Is there any way to search like that by django-ldapdb?

**Comment by zhuaiji** [comment]
I tried code below, it seems to be OK
`rootDN = request.GET.get('rootDN')`
   ` newSearchClass = CommonLdapObject.scoped(rootDN)`
   ` newSearchClass.search_scope = ldap.SCOPE_ONELEVEL`
   `resultList = newSearchClass.objects.all()`

**Comment by rbarrois** [comment]
Yeah, the design of django-ldapdb is to have models mapping objectclasses; thus, dumping the whole directory is not exactly a primary goal.

It looks like your work-around suits you, so I'm closing this; feel free to re-open if you need more help!
