### ISSUE TITLE
CONNECTION_OPTIONS doesn't work anymore

### ISSUE THREAD

**Issue by unixwitch** [django-ldapdb/django-ldapdb#114]
In previous versions of django-ldapdb (tested with 0.4.0) it was possible to configure connection TLS parameters in `DATABASES` like this:

```
        'TLS':    True,
        'CONNECTION_OPTIONS': {
            ldap.OPT_X_TLS: ldap.OPT_X_TLS_DEMAND,
            ldap.OPT_X_TLS_REQUIRE_CERT: ldap.OPT_X_TLS_DEMAND,
            ldap.OPT_X_TLS_CACERTFILE: '/app/tbx-ca.pem',
        },
```

As of 0.8.0, this no longer works:

```
  File "/usr/local/lib/python3.6/site-packages/ldapdb/backends/ldap/base.py", line 229, in get_new_connection
    if opt.lower() == 'query_timeout':
AttributeError: 'int' object has no attribute 'lower'
```

I can't seem to find any documentation on how TLS configuration is supposed to work, so I'm not sure if there's a different way to do this now...

**Comment by rbarrois** [comment]
Well, the tests for this have been disabled because they are actually complex to parse (previous versions used mockldap, which mocks the python-ldap library; we now use volatildap in order to work with a real LDAP server).

I'm fixing this now.
