### ISSUE TITLE
"verbose_name" doesn't work.

### ISSUE THREAD

**Issue by ikreb7** [django-ldapdb/django-ldapdb#117]
My code:

```python
    class LdapUser(ldapdb.models.Model):
        base_dn = "ou=people,dc=example,dc=org"
        object_classes = ['posixAccount', 'shadowAccount', 'inetOrgPerson']

        first_name = CharField('First Name', db_column='givenName')
        last_name = CharField('Last Name', db_column='sn')
        full_name = CharField('Full Name, db_column='cn')
        email = CharField('E-Mail', db_column='mail')
        phone = CharField('Phone Number', db_column='telephoneNumber', blank=True)
```

I tried also 

```python
    first_name = CharField(db_column='givenName', verbose_name='First Name')
```

but it still doesn't work. Maybe it is my fault, but I tried it with a normal model and it works.

**Comment by gojohnkevin** [comment]
This seems to 

> class LdapUser(ldapdb.models.Model):
    base_dn = "ou=people,dc=example,dc=org"
    object_classes = ['posixAccount', 'shadowAccount', 'inetOrgPerson']

    first_name = CharField('First Name', db_column='givenName')
    last_name = CharField('Last Name', db_column='sn')
    full_name = CharField('Full Name, db_column='cn')
    email = CharField('E-Mail', db_column='mail')
    phone = CharField('Phone Number', db_column='telephoneNumber', blank=True)

This is working for me.

**Comment by ikreb7** [comment]
Thanks for your answer, i will examine the problem.

**Comment by rbarrois** [comment]
@ikreb7 I've added some tests, I'm not able to reproduce your issue :/

Feel free to reopen this if need be :)
