### ISSUE TITLE
Error while running example: AttributeError: 'DatabaseCursor' object has no attribute 'close'

### ISSUE THREAD

**Issue by azuraka** [django-ldapdb/django-ldapdb#120]
Hi,
When running the following **command** for the given project:
**./manage_dev.py migrate --database='ldap'**

I get the following **error**:
**AttributeError: 'DatabaseCursor' object has no attribute 'close'**

Django v1.8. Tried with Django v1.9 and 1.10 as well. Got the same error.

**Comment by ikreb7** [comment]
Could you show us your database settings, please?

**Comment by ikreb7** [comment]
I didn’t response. Feel free to reopen this if the error still exists.
