### ISSUE TITLE
[enhancement] Support Django 1.11

### ISSUE THREAD

**Issue by kwill** [django-ldapdb/django-ldapdb#123]
I just ran into #122 ("NoneType object is not callable"). Creating this issue to get updates on support for Django 1.11.

~~In the meantime, perhaps add the Django versions you support to the README? As far as I can see that's >= 1.8 and < 1.11~~ (whoops, it's there already as pointed out below)

**Comment by ikreb7** [comment]
Look at the file README.rst

> django-ldapdb supports Django versions 1.8 to 1.10, and Python 2.7/3.4/3.5.


But I totally agree with you that we have to support soon Django 1.11, because the mainstream support for 1.10 is over. See here the [roadmap](https://www.djangoproject.com/weblog/2015/jun/25/roadmap/).

**Comment by pileofrogs** [comment]
I'm also working on django 1.11 and tried using django_ldapdb.  Looking forward to updates to django_ldapdb.

Thanks!
