### ISSUE TITLE
TypeError 'must be str, not None' in /ldap/ldapobject.py _ldap_call, line 263

### ISSUE THREAD

**Issue by guimaraesrodrigues** [django-ldapdb/django-ldapdb#124]
I'm receiving this error when trying to lookup for groups in LDAP database. I have no idea what is wrong and I'm pretty sure that my connection settings is ok. The user authentication works fine, but I need to retrieve the Groups so I can apply permissions in my views. 

My models.py:
import ldapdb.models

```python
class GrupoLdap(ldapdb.models.Model):
    """
    Class for representing an LDAP group entry.
    """
    # LDAP meta-data
    base_dn = "ou=Grupos,dc=cmc,dc=pr,dc=gov,dc=br"
    object_classes = ['posixGroup']

    # posixGroup attributes
    gid = IntegerField(db_column='gidNumber', unique=True)
    name = CharField(db_column='cn', max_length=200)
    members = ListField(db_column='memberUid')

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name
```

Do I need to declare some configuration for groups in settings.py?

**Comment by ikreb7** [comment]
Do you have imported the `ldapdb.models.fields`?

You need in your case:

    from ldapdb.models.fields import CharField, ListField, IntegerField

**Comment by guimaraesrodrigues** [comment]
@ikreb7 thanks for your answer! Yes, I have. Here is a screenshot from debug info (maybe it's helpful): 
![screenshot at 2017-06-19 13 19 56](https://user-images.githubusercontent.com/10090242/27295189-5ad2438c-54f2-11e7-87a0-6d0c7df94046.png)

**Comment by ikreb7** [comment]
Hey @guimaraesrodrigues , I guess that you have to check your settings. 

Your error message shows that  `conn_params` are empty, so this means, that the dict entries `'USER'` and `'PASSWORD'` are empty. [Here](https://github.com/django-ldapdb/django-ldapdb/blob/master/examples/settings.py) is a example how its look like.

**Comment by guimaraesrodrigues** [comment]
@ikreb7 You're right! In this project we are using [python-decouple](https://pypi.python.org/pypi/python-decouple) for our settings and booth arguments were None. Now I'm not receiving this error, but no list of groups or users is shown. These implementations are enough to make Django admin list all groups in my ldap datebase? Should I open a new issue to discuss this? I didn't find a documentation that explains the next step :/

**Comment by ikreb7** [comment]
At first, what did you change that the first problem is solved?

If I understand you correctly, your problem is that you don't see the ldap models at the django admin view. How looks your `admin.py`? Do you get a error message?

**Comment by ikreb7** [comment]
I didn’t response. Feel free to reopen this if the error still exists.
