### ISSUE TITLE
Possibility to remove attribute

### ISSUE THREAD

**Issue by moonwolf-github** [django-ldapdb/django-ldapdb#128]
Is there a way to remove attribute? In 389 server there is **nsAccountLock** attribute that needs to be removed to activate user account.

**Comment by rbarrois** [comment]
I'm not sure; you could try setting the value to ``None`` or to an empty list, but this might not be interpreted correctly.

If it doesn't work, would you mind opening a pull-request with the API you'd expect to use for this, and a test showing that if fails? This would help a lot to directly write the proper code :)

**Comment by rbarrois** [comment]
I can confirm that setting a field to an empty value will unset that attribute on the LDAP site, which should be what you requested.

I'm closing this issue, but please reopen it if you still have the issue!
