### ISSUE TITLE
Why ldapdb.models.Model models aren't listed on the sys.modules('app.models')?

### ISSUE THREAD

**Issue by gcavalcante8808** [django-ldapdb/django-ldapdb#135]
Hey Folks,

I just created a ListField inherited Class to work with listfield values as M2M relationship feel, but when I have models that have values for each other (memberOf backrefs, for example), normally I can just get the target model from sys.modules('app.models'); with ldapdb.models.Model, the model class isnt listed on the sys.modules('app.models') so I cant use it to circunvet the circular requirement.

My Field:
```
class MemberListField(ListField):
    """
    A memberListField that show DN as LdapStudent Entries.
    """
    def __init__(self, *args, **kwargs):
        self.klass = kwargs.pop('klass')

        super(ListField, self).__init__(*args, **kwargs)

    def get_obj_from_dn(self, dn, connection):
        value = dn.decode(connection.charset)
        uid = uidre.match(value).group('uid')
        return self.klass.objects.get(pk=uid)

    def from_ldap(self, value, connection):
        return [self.get_object_from_dn(dn, connection) for dn in value]

    def get_db_prep_save(self, value, connection):
        if not value:
            return None
        return [x.build_dn().encode(connection.charset) for x in value]
```

Models:

```
def related_class(klass):
    related = getattr(sys.modules.get('subscription.models', klass))
    return related

class LdapStudent(ldapdb.models.Model):
    """
    Class for representing an LDAP student entry.
    """
    base_dn = "ou=users," + settings.LDAP_DEFAULT_DN
    object_classes = ['inetOrgPerson', 'shadowAccount', 'moodleUser']

    _memberOf = local_fields.MemberListField('Cursos', db_column='memberOf', 
                                                                          klass=related_class('LdapCourse'),
                                                                          blank=True, null=True)

class LdapCourse(ldapdb.models.Model):
    """
    Class for representing an LDAP course entry.
    """
    # LDAP meta-data
    base_dn = "ou=ava," + settings.LDAP_DEFAULT_DN
    object_classes = ['organization', 'moodleCourse']
    students = local_fields.MemberListField('Alunos', db_column='courseStudent', blank=True,
                                                                                                      null=True, klass=LdapStudent)
```

## What to expect?

An object of class type from the requisited String.

## What Returns:

*** AttributeError: module 'subscription.models' has no attribute 'LdapCourse'

## Is There anyway to do the real prove?

Yes. Through `getattr(sys.modules['subscription.models'], 'MyOwnClass')` that yelds the MyOwnClass.

Thanks in advance.

**Comment by rbarrois** [comment]
Hi,

I don't think that accessing a model class through ``sys.modules`` is supported; have you tried using Django's [get_model](https://docs.djangoproject.com/en/2.0/ref/applications/#django.apps.AppConfig.get_model)?

**Comment by gcavalcante8808** [comment]
Hi,

I'll try to use get_model in the next weekend. Thanks for the tip.

**Comment by rbarrois** [comment]
Hope it worked for you :)

I'm closing this now to keep the issue list clean, let me know if you need more help!
