### ISSUE TITLE
'CharField' object has no attribute 'from_ldap'

### ISSUE THREAD

**Issue by rhoerbe** [django-ldapdb/django-ldapdb#140]
I am trying to get ldapdb working with a minimal model that is a subset of examples/. However when reading the data the compiler fails when sorting by dn.

The model:
````
class LdapUser(ldapdb.models.Model):
    base_dn = "dc=at"
    object_classes = ['inetOrgPerson']
    first_name = CharField(db_column='givenName')
    last_name = CharField("surname", db_column='sn')
    full_name = CharField(db_column='cn')
    email = CharField(db_column='mail')
````

The culprit seems to be the use of field.from:ldap() in https://github.com/django-ldapdb/django-ldapdb/blob/7dd88e68d356ed6e6ac9e4f9a92b3533fa668e7b/ldapdb/backends/ldap/compiler.py#L213

from_ldap() is member of ldapdb.models.fields.CharField, but the dn is an instance of django.db.models.fields.CharField.

What is the reason for this?

**Comment by rhoerbe** [comment]
I tried the 1.0, 0.9 and 0.8 releases, all have the same problem.
Python is 3.5

**Comment by rbarrois** [comment]
Oh, that looks like a bug!

Could you provide a minimal code sample that provokes the error?

**Comment by LennyLip** [comment]
@rbarrois I found this reason for this issue.  This happened if inheritance model of ldapdb.models.Model is not have a field with 'primary_key=True' , then sort_field [became 'dn' field](https://github.com/django-ldapdb/django-ldapdb/blob/40a835127a675a07b27aaa4621f2db617658bb02/ldapdb/backends/ldap/compiler.py#L209)

**Comment by peppelinux** [comment]
Same exception for me, same solution.

````
    uid = CharField(db_column='uid',
                    verbose_name="User ID",
                    primary_key=True)
````

now works, primary_key is needed there.
Django 2.0 with latest ldapdb from github.
