### ISSUE TITLE
TypeError: All provided fields *must* be text when bytes mode is off; got 'CN=XXX,CN=Users,DC=domain,DC=com'

### ISSUE THREAD

**Issue by ZeraICT** [django-ldapdb/django-ldapdb#141]
I am trying to make the migrations for the following code.

```python
class LdapUser(ldapdb.models.Model):
    base_dn = "CN=XXX,CN=Users,DC=domain,DC=com"
    object_classes = ['posixAccount', 'shadowAccount', 'inetOrgPerson']

    # inetOrgPerson
    first_name = CharField(db_column='givenName', blank=True)
    last_name = CharField(db_column='sn', blank=True)
    email = CharField(db_column='mail', blank=True)
    salutation = CharField(db_column='title', blank=True)
    phone = CharField(db_column='telephoneNumber', blank=True)
    mobile_phone = CharField(db_column='mobile', blank=True)
```

But somehow it does not work because my bytes mode is off(??). Is there something I can do about it?

**Comment by rbarrois** [comment]
Are you using Python2 or Python3?

If you're using Python2, you **must** provide "unicode" objects to the library; the simplest way is to add a ``from __future__ import unicode_literals`` at the top of your file; or to add a leading ``u`` to your text literals (e.g ``base_dn = u"CN=XXX,CN=Users,DC=domain,DC=com"``)

**Comment by rbarrois** [comment]
I hope the issue was fixed on your side :)

I'm closing the issue, let us know if you still see the bug!
