### ISSUE TITLE
Please switch to python-ldap

### ISSUE THREAD

**Issue by P-EB** [django-ldapdb/django-ldapdb#147]
Hi,

pyldap merged back with python-ldap project and thus deprecated itself. See https://github.com/pyldap/pyldap

Could you consider moving install_requirement to python-ldap. Mind that this would induce no need to recode/refactor anything, so far.

Cheers!

**Comment by mick-t** [comment]
I second this. I was updating my dependencies and pyldap says the following:

>The pyldap fork was merged back into python-ldap, and released as python-ldap 3.0.0.

**Comment by P-EB** [comment]
@rbarrois thanks! <3
