### ISSUE TITLE
Foreign Key  from a django model

### ISSUE THREAD

**Issue by LogX7** [django-ldapdb/django-ldapdb#154]
Hello 
i currently have a User2 Model, that has additional information, as well as a foreign key to the standard User Model
i want to start saving the standard User Model info in an ldap db, and wanted to know if i could still have the foreign key from User in User2

**Comment by peppelinux** [comment]
Try django generic relation instead of pure fk relation. For data replication from sql to ldap and viceversa you could implement presave and postdave signals or models save method overload

**Comment by peppelinux** [comment]
https://docs.djangoproject.com/en/2.0/ref/contrib/contenttypes/#generic-relations

https://docs.djangoproject.com/en/2.0/topics/db/models/#overriding-predefined-model-methods

https://docs.djangoproject.com/en/2.0/topics/signals/

These are jut a bunch of workaround. Ldapdb is not a standard sql db so pure fk relations to a db schema are not possible. I let other developer say some othercthings on this topic. Remember that signals and save method override acts like a trigger, generic relation instead produces relation based on registered app, in content type API. They all are applicative strategies to do such things

**Comment by peppelinux** [comment]
Reading closed Issues I found this very usefull resource:

https://hackriculture.fr/foreignkey-cross-database-avec-django.html

**Comment by LogX7** [comment]
i'm gonna test hackriculture method and get back to use
