### ISSUE TITLE
Access Data within a ListField

### ISSUE THREAD

**Issue by BaraHashesh** [django-ldapdb/django-ldapdb#156]
I'm trying to fetch data from a pre-established ldap database 
The Object i'm currently fetching has a **ListField** element
I'm capable of preforming query to check if a value exists in the element (__contains)
However I'm when the Object is fetched the **ListField** is empty, how can i solve this
Below is my code for the object 

```python
class Group(ldapdb.models.Model):
    """
    Class for representing an LDAP user entry.
    """
    # LDAP meta-data
    base_dn = "ou=Group,dc=exmple,dc=org"
    object_classes = ['top', 'posixGroup']

    # top
    userid = fields.CharField(db_column='userid')

    # posixGroup
    cn = fields.CharField(db_column='cn')
    gidNumber = fields.IntegerField(db_column='gidNumber')

    # non object_classes fields
    displayname = fields.CharField(db_column='displayname')
    memberuids = fields.ListField(db_column='memberuid')`

def test(request):
    return HttpResponse(Group.objects.get(cn='Accounting').memberuids)`

**Comment by peppelinux** [comment]
Please tell us more informations like django version used and if the django node can bind ldap and fetch that attributes though ldapsearch utility (it could be a ACL filter).

ListField have methods to store and get that information if available

**Comment by BaraHashesh** [comment]
The django version used is 2.0.7.

Binding and fetching data worked just fine when it was tested.

When i tried to edit an object in code and saving changes after that, the changes are reflected correctly to the data base with no problems, however some values are indeed fetched as empty string when dealing with them directly in the django side even though querying over them with **__contains** option or equal option works fine when using the **.filter** option for the select query , currently i'm unable to further test things out since i'm incapable of accessing the server right now (company personal server) [currently off on weekend till sunday], and the **ldif** file of the data base that i exported is not being imported correctly to my local ldap server due to syntax issues that i'm trying to solve (don't have any experince when dealing directly with an ldap data base).

**Comment by peppelinux** [comment]
For this you have to check for Field Lookups related to ListFields,
try to read ldap.fields sources to get answers

**Comment by BaraHashesh** [comment]
I've fixed the problem
it appears that the **ldif** file that i was provided contained errors in the names for the data base columns
(errors such as upper case characters where replaced with lower case ones)

**Comment by rbarrois** [comment]
@BaraHashesh so the mistake was that you tried to fetch ``memberuids`` instead of ``memberUids``? If that's the case, can you close the issue?

Thanks :)
