### ISSUE TITLE
Build Distinguished Name

### ISSUE THREAD

**Issue by BaraHashesh** [django-ldapdb/django-ldapdb#157]
I'm currently working with a pre-built ldap data base.
I've built the models for the data base by hand in general.
Fetch as well as search query's works just fine however when i try to change an entity (element) or create a one in the data base a  **Could not build Distinguished Name** exception is raised bellow is my code 

`
class People(ldapdb.models.Model):

    #Class for representing an LDAP People entry.

    base_dn = "ou=people,dc=example,dc=org"
    object_classes = ['top', 'inetOrgPerson', 'posixAccount']

    # top
    userid = fields.CharField(db_column='userid')

    # inetOrgPerson
    cn = fields.CharField(db_column='cn')
    sn = fields.CharField(db_column='sn')

    # posixAccount - shadowAccount
    gidNumber = fields.IntegerField(db_column='gidNumber')
    homeDirectory = fields.CharField(db_column='homeDirectory')
    uid = fields.CharField(db_column='uid')
    uidNumber = fields.IntegerField(db_column='uidNumber')

    # non object classes fields
    sambaSID = fields.CharField(db_column='sambaSID')
    email = fields.CharField(db_column='mail')
`

`
    p = People.objects.all()[0]

    p.sambaSID = 'Some-Value'

    p.save()
`

**Comment by rbarrois** [comment]
Yes, you need to identify which field is your "primary key": the object's distinguishedName will be ``$FIELD=$VALUE,ou=people,dc=example,dc=org``.

For instance, if your users are stored as ``userid=x,ou=people,dc=example,dc=org``, then you'll have to add ``primary_key=True`` to the ``userid`` field.
