### ISSUE TITLE
Fail to update multi-PK objects

### ISSUE THREAD

**Issue by Natureshadow** [django-ldapdb/django-ldapdb#159]
If you have a model with multiple PKs (which is supported by ldapdb), updating one of those models (in a `save()` operation fails if there are two objects where *one* of the PKs match, because when retrieving the old object for comparison, only one of the PK fields is used.

It seems that the DN could be used instead, as the object still carries the old DN (and manual DN changes aren't supported anyway).

**Comment by rbarrois** [comment]
How would a multi-pk field work on the LDAP side?

The ``django-ldapdb`` notion of a primary key is, basically, *your primary key is the field that defines the ``rdn`` part of the ``distinguishedName`` of your object*.
For instance, if a user is located inside ``ou=people``, and its primary key is the ``uid`` field, then its ``distinguishedName`` will be ``uid=X,ou=people,...``.

Unless I'm mistaken, the tolerance for multi-PK objects looks more like a bug than an expected feature; could you share the layout of the model you're using, both on the Django and LDAP sides?

**Comment by Natureshadow** [comment]
You are mistaken, at least for the most part.

Yes, the PK makes up the RDN part of the LDAP obejct. No, the RDN part cannot only contain one field. RDNs are multi-valued and can consist of any number of field=value pairs. E.g., `uid=nik+cn=Dominik George` is a perfectly valid RDN, consisting of the `cn` and `uid` attributes of the object.

From RFC 4514:

```
      RelativeDistinguishedName ::= SET SIZE (1..MAX) OF
          AttributeTypeAndValue

      AttributeTypeAndValue ::= SEQUENCE {
          type  AttributeType,
          value AttributeValue }
```

**Comment by rbarrois** [comment]
@Natureshadow Oh, thanks for the information; I wasn't aware of that fact (I've only taken over maintenance of django-ldapdb for a couple of years now, so I might not know yet every feature!).

That's indeed a bug, I'll try to look into your PR soon :)

If you had the time to write some kind of test (or a skeleton for that), maybe in the ``examples/`` area, that would be very helpful!
