### ISSUE TITLE
Cannot save anymore in 1.1.0

### ISSUE THREAD

**Issue by Natureshadow** [django-ldapdb/django-ldapdb#161]
Sine the rewrite with LdapFieldMixin, the ldap library sometimes complains that it expects bytestrings instead of strings in the modlist.

I think this is because some field models lost their encoding routine - e.g. CharField is lacking the get_prep_value encoding it to bytes that TextField has.

```
File "/srv/www/ticdesk/venv/lib/python3.5/site-packages/django/db/models/manager.py" in
manager_method
  82.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/srv/www/ticdesk/venv/lib/python3.5/site-packages/django/db/models/query.py" in
create
  417.         obj.save(force_insert=True, using=self.db)

File "/srv/www/ticdesk/venv/lib/python3.5/site-packages/ticdesk_account/models.py" in save
  329.         super(TeckidsPerson, self).save(*args, **kwargs)

File "/srv/www/ticdesk/venv/lib/python3.5/site-packages/django/db/models/base.py" in save
  729.                        force_update=force_update, update_fields=update_fields)

File "/srv/www/ticdesk/venv/lib/python3.5/site-packages/django/db/models/base.py" in
save_base
  759.             updated = self._save_table(raw, cls, force_insert, force_update, using,
update_fields)

File "/srv/www/ticdesk/venv/lib/python3.5/site-packages/ldapdb/models/base.py" in
_save_table
  117.             connection.add_s(new_dn, new_values)

File "/srv/www/ticdesk/venv/lib/python3.5/site-packages/ldapdb/backends/ldap/base.py" in
add_s
  277.         return cursor.connection.add_s(dn, modlist)

File "/srv/www/ticdesk/venv/lib/python3.5/site-packages/ldap/ldapobject.py" in add_s
  428.     return self.add_ext_s(dn,modlist,None,None)

File "/srv/www/ticdesk/venv/lib/python3.5/site-packages/ldap/ldapobject.py" in add_ext_s
  413.     msgid = self.add_ext(dn,modlist,serverctrls,clientctrls)

File "/srv/www/ticdesk/venv/lib/python3.5/site-packages/ldap/ldapobject.py" in add_ext
  410.     return
self._ldap_call(self._l.add_ext,dn,modlist,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))

File "/srv/www/ticdesk/venv/lib/python3.5/site-packages/ldap/ldapobject.py" in _ldap_call
  313.         result = func(*args,**kwargs)

Exception Type: TypeError at /account/register
Exception Value: ('Tuple_to_LDAPMod(): expected a byte string in the list', '')
```

**Comment by peppelinux** [comment]
Probably the fault is in the ListField.

I had the same issue, I Coded MultiValudField in PR https://github.com/django-ldapdb/django-ldapdb/pull/152

**Comment by Natureshadow** [comment]
Umm… Well, in any case, it helps a lot if you can read diffs the right way around :D. TextField, of course, doesn't exist in django-ldapdb.

**Comment by peppelinux** [comment]
This issue raises when using Django 2.0.
I Fixed this in my approach and also introduced a better way to read the field, nothing prevents you to take what you need from my code to produce a renewed ListField that works for you.

All this should drive us to next release! ;)

**Comment by Natureshadow** [comment]
Tracing through your code (which is not so easy in your PR because it mixes tons of unrelated stuff) somehow doesn't look like your MultiValueField is in any way different in that regard. Maybe you can create separate PRs for separate issues, so one can see which of your changes actually tackles this problem?

**Comment by peppelinux** [comment]
You're right, I made my PR first of all for MultiValueField, then other pushes filled the stacks!
My excuse for that entropy, I'm sharing my work as it is but I'll fix it as soon as I have a bit of time to do it

**Comment by rbarrois** [comment]
@Natureshadow that would be a nasty bug indeed. Can you share more details about the kind of field you're seeing the failure with?
Maybe run a debugger and take a look at the contents of ``modlist`` when we reach ``LDAPObject.add_ext()``?
