### ISSUE TITLE
Followup from "Please provide the tests files in your releases"

### ISSUE THREAD

**Issue by P-EB** [django-ldapdb/django-ldapdb#163]
Hi,

@rbarrois I'm sorry but your commit 612ad65 didn't completely fix issue #146 :(

The manifest still excludes `manage_dev.py` that is used to run the tests, and `tox.ini` that seems useful for these tests too.

Could you also include these?

Thanks :)

**Comment by rbarrois** [comment]
I'll do my best; can you provide me with a simple routine I could use to actually check on my side that the test files are properly packaged and integrated?

Best case, something I could add to our CI ;)

**Comment by P-EB** [comment]
Do you prefer a bash script or a perl one?

**Comment by rbarrois** [comment]
Whatever; the best would be a simple description of the process you usually go through to run those tests (e.g ``python setup.py sdist; python -m venv new_venv; . ./new_venv/bin/activate; pip install dist/...; ...``

**Comment by P-EB** [comment]
The tests are ran in debian packaging build process, the command is `python3 setup.py test`.

See, eg https://ci.debian.net/data/autopkgtest/unstable/amd64/d/django-ldapdb/549032/log.gz

The dependencies are installed using apt. The dependency tree is computed from the control file of a package : here, https://tracker.debian.org/media/packages/d/django-ldapdb/control-1.0.0ds-1

**Comment by rbarrois** [comment]
@P-EB Done.
Please note that the supported way to run the test suite is ``make test``, not ``python3 setup.py test``; you might want to adjust your control files accordingly.
