### ISSUE TITLE
Travis tests fail on Python 3.5

### ISSUE THREAD

**Issue by Natureshadow** [django-ldapdb/django-ldapdb#168]
On Python 3.5, the tests fail because of a PendingDeprecationWarning in the imp module. However, this is explicitly ignored in `PYWARNINGS` in the `Makefile`.

@rbarrois Do you have any idea why this is not ignored in Python 3.5?

**Comment by rbarrois** [comment]
This has been fixed by commit 44a452ae05aa542b8044efc93bdb90a23aca1f73 :)
