### ISSUE TITLE
TimestampField - TypeError a float is required when save from ModelAdmin

### ISSUE THREAD

**Issue by peppelinux** [django-ldapdb/django-ldapdb#181]
#### Description
Type Error when save from a ModelAdmin form using ldapdb's DateTimeField

##### Model code
```python
schacExpiryDate = DateTimeField(db_column='schacExpiryDate',
                                    help_text=_('date from which the set of data is to be considered invalid'),
                                    blank=True, null=True)
```

##### The issue
The exception raises in ldapdb/models/fields.py ,  at line 357
```
def datetime_from_timestamp(ts):
    return timezone.utc.localize(datetime.datetime.utcfromtimestamp(ts)) 
```

#### Environment
Django 2.0.7

**Comment by Natureshadow** [comment]
While the title talks about TimestampField, the issue itself talks about DateTimeField, which are two different things. utcfromtimestamp takes a UNIX tiemstamp, DateTimeField returns a datetime object.

Please clarify ☺

**Comment by Natureshadow** [comment]
Closed as invalid.
