### ISSUE TITLE
How can I add user to a group?

### ISSUE THREAD

**Issue by kwill** [django-ldapdb/django-ldapdb#188]
I would like to add/remove LDAP users from an LDAP group, via ldapdb. I can't find any documentation around this. Is it possible?

**Comment by Natureshadow** [comment]
Why do you think this operation should not be possible?

I somehow feel you have not read what ldapdb is ☺.

**Comment by peppelinux** [comment]
@kwill use memberof overlay and write to its OU, you should get operation attributes with memberOf as a list

**Comment by Natureshadow** [comment]
I, for one, would simply add the user DN to the member attribute of the group…
