### ISSUE TITLE
Failure with OpenLDAP 2.5.5

### ISSUE THREAD

**Issue by sergiodj** [django-ldapdb/django-ldapdb#203]
#### Description

I'm working towards getting OpenLDAP 2.5.5 on Ubuntu Impish, and currently django-ldapdb is failing to run its tests because the `hdb` backend has been removed from the OpenLDAP 2.5.x series.

#### To Reproduce

Build OpenLDAP 2.5.x, and run django-ldapdb's tests against it.

#### Environment
*Describe the platform where the issue occurred, for easier analysis*

- *LDAP server*: OpenLDAP 2.5.5
- *Operating system*: Ubuntu Impish (development version)

#### Notes

In case you're interested, here is the full test log:

https://autopkgtest.ubuntu.com/results/autopkgtest-impish/impish/armhf/d/django-ldapdb/20210622_014821_c2372@/log.gz

**Comment by sergiodj** [comment]
It seems this was a problem related to another package that's being used during the tests: volatildap.  Therefore, I'm closing this issue.

**Comment by rbarrois** [comment]
That's quite likely indeed.
Since I'm the maintainer of both packages, I'll check here once `volatildap` is fixed anyway!

**Comment by sergiodj** [comment]
Thanks, @rbarrois.  I submitted a PR with a possible fix to volatildap here a few days ago.
