### ISSUE TITLE
ValueError: read-only option

### ISSUE THREAD

**Issue by joenatan** [django-ldapdb/django-ldapdb#210]
I have the following error message:
ValueError: read-only option on line lib\site-packages\ldap\ldapobject.py, line 128, in _ldap_call

After long debugging and analyzing, I have not found a solution or error.

Any ideas?

**Comment by peppelinux** [comment]
It seems something up to python-ldap that's a dependency in this project

Can you descrive how and when this exception raises in you implementation?

**Comment by joenatan** [comment]
I have found the problem. It has not to do with django-ldapdb, but with the library ldap itself.

ValueError: read-only option

Means that you try to set a LDAP constant (ldap.set_option) which is read-only. Actually quite simple to understand (in retrospect :-)).
