### ISSUE TITLE
Only flat directory tree is supported

### ISSUE THREAD

**Issue by tothandor** [django-ldapdb/django-ldapdb#3]
You won't be able to edit any entity deeper than the base_dn, because models/base.py:build_rdn builds up rdn concatenating only the primary key fields.

For example. Let base_dn be ou=Users,dc=example,dc=com.
Let's have a user with the following dn: cn=username,ou=Finance,ou=Users,dc=example,dc=com

The primary key column is cn, build_rdn will generate the following rdn: cn=username, thus the full dn will be cn=username,ou=Users,dc=example,dc=com **without ou=Finance**.

A possible solution of mine is to strip the base_dn and current primary key (cn=username) from the whole dn, and prefix the rest with the new one.

Bests,
Andor

**Comment by moserhans** [comment]
Is this patch - or something with the same functionality - included here by now?
I just started with ldapdb and stumbled over the very same problem how to include a tree level between rDN and baseDN on write.

**Comment by salvorapi** [comment]
+1

**Comment by sysmoon** [comment]
+1
i have no idea.. how to solve?
