### ISSUE TITLE
How different is this from django_auth_ldap and what is the best solution

### ISSUE THREAD

**Issue by rajalokan** [django-ldapdb/django-ldapdb#34]
Hi All

We have an existing ldap implementation (using django_auth_ldap & APIs to execute raw ldap calls). We are in process of rewriting our LDAP part. I very much like this approach of manipulating with something similar to Django models. I have few questions though.
- I can get basic get/filter/delete operation but how do we do permissions. Suppose I want to know all groups of a a certain user(mail=foo@bar.com,dc=example,dc=com) what should be the best way. With django_auth_ldap this is a lot obvious.
- There is no login/authenticate backend. How to integrate LdapBackend with this.
- Should I use LdapUser model for ldap operation only? Is is a good practice to have foreign key in ldapdb.models? I don't see ForeignKey inside ldapdb.models.fields.
  This is mostly to draw line between LdapUser and django.contrib.auth.models.User. I was hoping if we can replace auth_user with LdapUser.

These above points leads me to a hybrid approach of using both django-ldapdb and django_auth_ldap. What do you guys think of it?

**Comment by chronossc** [comment]
@jlaine  I know it is a old issue but you see possible a authentication backend similar to django-auth-ldap but using ldapdb models?

**Comment by jlaine** [comment]
Sure, you could write an authentication backend based on ldapdb yourself. It would however have to be for a very specific usecase as django-auth-ldap covers the most common cases. In any case this is beyond the scope of ldapdb.
