### ISSUE TITLE
Please package examples/tests to pypi

### ISSUE THREAD

**Issue by g1itch** [django-ldapdb/django-ldapdb#48]
django-ldapdb-0.3.2 on pypi doesn't contain examples and tests. You can add it through MANIFEST.in:
```diff
diff --git a/MANIFEST.in b/MANIFEST.in
index b44eea6..e5e36c2 100644
--- a/MANIFEST.in
+++ b/MANIFEST.in
@@ -1,3 +1,5 @@
 include AUTHORS
 include LICENSE
 include README.md
+recursive-include examples *
+include settings.py manage.py
```

**Comment by rbarrois** [comment]
The ``django-ldapdb`` package on PyPI should only contain the actual code and docs; tests do not belong there, in my opinion.
