### ISSUE TITLE
ListField fails with duplicate values in iterable

### ISSUE THREAD

**Issue by aogier** [django-ldapdb/django-ldapdb#57]
Hi, when having a field like:

cn = ListField(db_column='cn')

trying to save eg. ['foo', 'bar', 'bar'] lead to a protocol error because duplicate value. Can't tell ATM if duplicates are allowed on a per-attribute basis, don't think anyway as it is really pointless in respect to RFC2251 : "the order of attribute values within the vals set is undefined and implementation-dependent, and MUST NOT be relied upon."
Maybe simply returning sets from ListField field class eg. from_ldap and get_db_prep_save ? not sure

thank you, ciao

**Comment by peppelinux** [comment]
I coded this after experiencing issues with ListField in Django 2

https://github.com/django-ldapdb/django-ldapdb/pull/152
