### ISSUE TITLE
Cant Connect to a Active Directory or a Ldap Server through a SSL or TLS connection

### ISSUE THREAD

**Issue by gcavalcante8808** [django-ldapdb/django-ldapdb#58]
Hello Folks,

I Can't connect to a Active Directory server using the ldapdb module. Everytime I try, the following error occurs:

'info': '000004DC: LdapErr: DSID-0C0906E8, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1db1', 'desc': 'Operations error'}.

After this, I tried to turn the TLS on through the CONNECTION_OPTIONS:

```
'ldap': {
    'ENGINE': 'ldapdb.backends.ldap',
    'NAME': 'ldaps://IP/',
    'USER': 'mydn',
    'PASSWORD': 'mypasswd',
    'CONNECTION_OPTIONS': {
            'TLS': True,
    }
```

}

But The same error ocurred.

Currently, all my django apps that relies on ldap to perform something, uses the following options for ldap (global, not connection specfic):

```
    ldap.set_option(ldap.OPT_REFERRALS, 0)
    ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, 0)
```

With this, I can access the Active Directory Normally.

If I put these options immediately after the ensure method(line 98, base.py module), all works fine and all queries works very well.

```
def ensure_connection(self):
    if self.connection is None:
        ldap.set_option(ldap.OPT_REFERRALS, 0)
        ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, 0)
```

So, I ask: How to pass arguments or get active directory integration to work on ldapdb?

Thanks in advance.

**Comment by rbarrois** [comment]
Sorry for the multi-year lag; it seems that this issue has been solved for you, so I'll simply close this ;)

Feel free to reopen it if you're still facing the bug!
