### ISSUE TITLE
Scoping schema is causing a Conflict

### ISSUE THREAD

**Issue by switchtower** [django-ldapdb/django-ldapdb#77]
Hello,
I've been using django-ldapdb for a while now, and just recently we upgraded our project to django 1.7.  After doing so, we discovered that we were getting the following error when we try to scope our lookups for our RADIUS config:
`RuntimeError: Conflicting 'ldapradius_cn_192.168.28.0/24_cn_clients_cn_radius_dc_int_dc_switchtower_dc_com' models in application 'radius': <class 'radius.models.LdapRADIUS_cn_192.168.28.0/24_cn_clients_cn_radius_dc_int_dc_switchtower_dc_com`

It appeared to be similar to this issue with django: https://code.djangoproject.com/ticket/22280

Let me know if there is any further information you need from me to get this figured out.

Keep up the good work by the way :)

**Comment by jlaine** [comment]
An example of your code is the very least we will need, or even better a additional testcase for the test suite which illustrates the problem.

**Comment by ikreb7** [comment]
You never answered so I will close this issue. Feel free to reopen it.
