### ISSUE TITLE
Use / option to use ReconnectLDAPObject to survive temporary LDAP issues?

### ISSUE THREAD

**Issue by dctrud** [django-ldapdb/django-ldapdb#80]
When faced with temporary LDAP outage it'd be nice if ldapdb used or gave the option to use ReconnectLDAPObject which will automatically retry a connection.

Something like:

`ldapdb/backends/ldap/base.py`

``` python
def ensure_connection(self):
    if self.connection is None:
        #self.connection = ldap.initialize(self.settings_dict['NAME'])
        self.connection = ldap.ldapobject.ReconnectLDAPObject(
            self.settings_dict['NAME'],
            retry_max=10)
...
```

.. but with the retry settings configurable.

Is this something that might be accepted as a PR?

**Comment by charlesfg** [comment]
@dctrud this setup fix temporary problems like the errors that appear like : 

```
SERVER_DOWN at /admin/contaunificada/grupoldap/add/
{'desc': "Can't contact LDAP server"}
```
???

Thanks!

**Comment by dctrud** [comment]
It did fix some transient errors for us when there was a connection break due to high load on the ldap server. However I'm not using it in production. We switched away from ldapdb to direct interaction with the ldap directory for other reasons.

**Comment by rbarrois** [comment]
This would be a nice enhancement indeed ;)

I'd be happy to merge such a PR :smile:
