### ISSUE TITLE
IntegerField has invalid lookup: in

### ISSUE THREAD

**Issue by mdemicheli** [django-ldapdb/django-ldapdb#81]
I'm starting to work with LDAP and using this app (thanks @jlaine!) I'm developing a django site to help me manage my LDAP db. Following the examples, I've created an LdapGroup model but instead of making the cn the pk, I chose the gidNumber. All works just fine but when deleting a group. I get an  "TypeError: IntegerField has invalid lookup: in". I've found this IntegerField definition (**/ldapdb/models/fields.py**):

```python
    def get_prep_lookup(self, lookup_type, value):
        "Perform preliminary non-db specific lookup checks and conversions"
        if lookup_type in ('exact', 'gte', 'lte'):
            return value
        raise TypeError("IntegerField has invalid lookup: %s" % lookup_type)
```

I've fixed the error simply by adding 'in' to that tuple. The question is: shouldn't be there by default? Or it has something to do with how LDAP works?

**Comment by rbarrois** [comment]
Looks like a bug ;)

This might be fixed as a side-effect of the current work on support for Django 1.10.
