### ISSUE TITLE
Field value used in model DN is not escaped

### ISSUE THREAD

**Issue by keto** [django-ldapdb/django-ldapdb#82]
I'm getting a lot of LDAPErrors like

```
{'info': 'invalid DN', 'desc': 'Invalid DN syntax'}
```

because there are some bad characters in the values used for the models primary key.

Should the `Model.build_rdn()` run `ldap.dn.escape_dn_chars()` on the primary key field value?

**Comment by rbarrois** [comment]
Would you have an example of the code / model / values causing the issue?

**Comment by keto** [comment]
I need check if this still happens with pyldap and the latest version.

**Comment by ikreb7** [comment]
Do you still have the problem? Please give more information like models/values or test cases.

**Comment by ikreb7** [comment]
Ok, I close this issue. Feel free to reopen it if you still have the problem.
