### ISSUE TITLE
Looking for new maintainers

### ISSUE THREAD

**Issue by jlaine** [django-ldapdb/django-ldapdb#84]
Even though I have not needed LDAP for any of my projects for several years, I tried to continue to support newer Django versions and merge fixes contributed by users. It has now reached the point where I consider the project would best be served by someone else (ideally more than one person) taking over.  If you are interested, please reply to this issue so we can arrange transfering code + issues.

**Comment by rbarrois** [comment]
As discussed by email, count me interested :)

**Comment by jlaine** [comment]
Excellent news @rbarrois, it's much appreciated :)

I have moved django-ldapdb to its own organization to facilitate the transfer.
