### ISSUE TITLE
ldapdb/tests.py will break in django 1.9

### ISSUE THREAD

**Issue by midnightlynx** [django-ldapdb/django-ldapdb#86]
The `Constraint` class from django's private API was deprecated in Django 1.7.
They replaced it with the public and documented `Lookup` class.
https://docs.djangoproject.com/en/1.8/howto/custom-lookups/

`Constraint` will be completely removed in Django 1.9, and ldapdb/tests.py uses it a lot in the `WhereTestCase`. So to maintain compatibility, the tests needs to be majorly rewritten to test without using it.

Since Django no longer supports any versions before 1.7, it should not be necessary for the new testing approach to be compatible with versions older than that.

**Comment by jlaine** [comment]
Have you seen issue #84 ?

**Comment by midnightlynx** [comment]
I have. I don't really think I have the time to take that on, but I'll consider it.

**Comment by midnightlynx** [comment]
I put in a pull request to fix this.

**Comment by rbarrois** [comment]
Fixed in 4c9b4fb. Thanks!
