### ISSUE TITLE
I can't get exclude using icontains distinguishedName.

### ISSUE THREAD

**Issue by markrlondon** [django-ldapdb/django-ldapdb#89]
I tried to do the following:

q = LdapGroup.objects.exclude(distinguishedName__icontains='Fiscal')

Is this supported?  For me, when I do this, "q" ends up with an empty queryset.
If I loop through the queryset and print the distinguishedName field, it properly shows the strings for distinguishedName, as contained in the LDAP database.   My brute force solution, was to do the filtering, by:

q = LdapGroup.objects.all()
        for z in q:
            if 'Fiscal' in z.distinguishedName:
                q = q.exclude(pk=z.pk)

I'm sure there is a more elegant way of doing this on one line.  Nevertheless, it would be nice if exclude would work. :)  Thanks.

**Comment by rbarrois** [comment]
I'm afraid the LDAP protocol only allows full equality lookups on distinguished names:

https://tools.ietf.org/html/rfc4517#section-3.3.9
https://tools.ietf.org/html/rfc4517#section-4.2.15
>    The distinguishedNameMatch rule is an equality matching rule.

You may be able to perform your lookups on the actual field used to build the distinguished name, e.g:

```q = LdapGroup.objects.exclude(name__icontains="Fiscal")```
